---

- name: install apache2
  apt:
    name: apache2
    state: present

- name: change index.html
  template:
    src: index.html.j2
    dest: /var/www/html/index.html

- name: add style.css
  template:
    src: style.css.j2
    dest: /var/www/html/style.css