- hosts: webserver
  become: yes
  user: "{{ user }}"
  gather_facts: no
  pre_tasks:
    - name: update packages
      raw: apt update && apt upgrade -y
    - name: install python3 packages
      raw: apt install -y python3 python3-pip python3-apt
  vars_files:
    - vars.yml


- hosts: webserver
  become: yes
  user: "{{ user }}"
  roles:
    - cloudwatch_agent
    - apache2
    - certbot
  vars_files:
    - vars.yml